<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="-INV007684-" name="Test" tests="2" failures="2" timestamp="3 Jan 2019 19:36:17 GMT" time="62.133" errors="0">
  <testcase name="SoapTest" time="61.978" classname="BookTests.Tests_soa">
    <failure type="java.lang.AssertionError" message="expected [FAILED] but found [FINISHED]">
      <![CDATA[java.lang.AssertionError: expected [FAILED] but found [FINISHED]
	at BookTests.Tests_soa.SoapTest(Tests_soa.java:31)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- SoapTest -->
  <testcase name="singletestrunner" time="0.078" classname="BookTests.UnitTestRunner">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at BookTests.UnitTestRunner.singletestrunner(UnitTestRunner.java:27)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- singletestrunner -->
</testsuite> <!-- Test -->
